"""Source-authority dispatch table.

Maps topic IDs to DispatchPlan instances that declare which sources are
authoritative (primary), which are phrasing-reference only (secondary),
and which are contextual enrichment (tertiary).

This is hardcoded for the demo tier. Production path: promote to
config/source_authority.yaml, reviewed quarterly by Product Marketing +
Compliance + General Counsel (docs/architecture.md §5.3).
"""
from __future__ import annotations

from shared.models import DispatchPlan, Tier

# ---------------------------------------------------------------------------
# Dispatch table — one entry per topic_id used by the classifier.
# Sources available in the demo tier:
#   compliance_store   S3 prefix compliance/  (SOC2 bridge, ISO cert PDFs + JSON sidecars)
#   product_docs       S3 prefix product-docs/ (whitepapers, feature markdown)
#   prior_rfps         S3 prefix prior-rfps/   (phrasing reference ONLY — never factual authority)
#   customer_refs_db   DynamoDB CustomerRefs   (hard-rule #4 gate)
#   seismic            mock_sources Lambda /seismic/content  (Phase C)
#   gong               mock_sources Lambda /gong/calls       (Phase C)
#   deal_desk          not wired in demo — pricing always force_tier=RED
# ---------------------------------------------------------------------------

DISPATCH_TABLE: dict[str, DispatchPlan] = {
    # Compliance certifications — compliance_store is the only factual authority.
    "soc2": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        tertiary=["seismic"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),
    "iso27001": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),
    "fedramp": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),
    "gdpr": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),
    "dpa": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),

    # Encryption and key management — product_docs is authoritative.
    "encryption_at_rest": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
        corroboration_required=True,
    ),
    "encryption_in_transit": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
        corroboration_required=True,
    ),
    "key_management": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
        corroboration_required=True,
    ),

    # Identity and access — product_docs + optional Seismic enrichment.
    "sso": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
        tertiary=["seismic"],
    ),
    "mfa": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
        tertiary=["seismic"],
    ),
    "scim": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
    ),

    # Operational resilience.
    "dr_bcp": DispatchPlan(
        primary=["product_docs", "compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),
    "incident_response": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),

    # Secure development.
    "ssdlc": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
    ),
    "pentest": DispatchPlan(
        primary=["compliance_store"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),
    "sbom": DispatchPlan(
        primary=["product_docs"],
        secondary=["prior_rfps"],
    ),

    # Data residency — both compliance and product docs are authoritative.
    "data_residency": DispatchPlan(
        primary=["compliance_store", "product_docs"],
        secondary=["prior_rfps"],
        corroboration_required=True,
        max_tier_without_primary=Tier.AMBER,
    ),

    # Pricing — never auto-generated. Commercial desk owns.
    "pricing": DispatchPlan(
        primary=["deal_desk"],
        force_tier=Tier.RED,
        reason="pricing_never_autogenerated",
    ),

    # Customer references — CustomerRefs DB is the only authority.
    "customer_reference": DispatchPlan(
        primary=["customer_refs_db"],
        tertiary=["prior_rfps"],  # phrasing reference only
    ),
}

# Used when no topic matches. Searches product_docs as a reasonable default.
DEFAULT_DISPATCH_PLAN = DispatchPlan(
    primary=["product_docs"],
    secondary=["prior_rfps"],
    tertiary=["seismic"],
    corroboration_required=False,
)


def get_dispatch_plan(topics: list[str]) -> DispatchPlan:
    """Merge dispatch plans for all matched topics. Most restrictive settings win.

    Source lists are unioned in order (primary, secondary, tertiary).
    force_tier propagates if any topic forces it.
    corroboration_required=True if any topic requires it.
    max_tier_without_primary takes the strictest (lowest) tier.
    """
    plans = [DISPATCH_TABLE[t] for t in topics if t in DISPATCH_TABLE]
    if not plans:
        return DEFAULT_DISPATCH_PLAN

    tier_order = {Tier.GREEN: 2, Tier.AMBER: 1, Tier.RED: 0}

    def _union(field: str) -> list[str]:
        seen: dict[str, None] = {}
        for p in plans:
            for s in getattr(p, field):
                seen[s] = None
        return list(seen)

    return DispatchPlan(
        primary=_union("primary"),
        secondary=_union("secondary"),
        tertiary=_union("tertiary"),
        corroboration_required=any(p.corroboration_required for p in plans),
        max_tier_without_primary=min(
            (p.max_tier_without_primary for p in plans),
            key=lambda t: tier_order[t],
        ),
        force_tier=next((p.force_tier for p in plans if p.force_tier), None),
        reason="; ".join(p.reason for p in plans if p.reason) or None,
    )
